version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:30"
    reviewers:
      - "manuelkienlein"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:30"
    reviewers:
      - "manuelkienlein"
    open-pull-requests-limit: 5
